### ISSUE TITLE
Error while saving markup: Reference xxxx only accepts ids of type xxxx 

### ISSUE THREAD

**Issue by MichielArts** [joerob319/imageMarker#1]
Hi Joe, i am working on using this widget for a major client. Following error occurs when i press save. Did i misconfigure or is it a bug? I can provide screenshots in private mail if needed.

`com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"Map(OLL.LocatieImage_OpnameItem -> 38562071809360177)","type":"ChangeAction"}', all database changes executed by this action were rolled back
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:108)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"Map(OLL.LocatieImage_OpnameItem -> 38562071809360177)","type":"ChangeAction"}', all database changes executed by this action were rolled back
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:23)

Caused by: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"Map(OLL.LocatieImage_OpnameItem -> 38562071809360177)","type":"ChangeAction"}', all database changes executed by this action were rolled back
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.processErrorState(CoreActionHandlerImpl.scala:153)

Caused by: java.lang.IllegalArgumentException: requirement failed: Reference 'OLL.LocatieImage_OpnameItem' only accepts ids of type 'OLL.OpnameItem' (Id '[MendixIdentifier:: id=38562071809360177 objectType=OLL.LocatieImage entityID=137]' is not allowed).
	at scala.Predef$.require(Predef.scala:337)
	at com.mendix.basis.objectmanagement.member.MendixObjectReferenceImpl.setValue(MendixObjectReferenceImpl.scala:35)
	at com.mendix.basis.action.user.Changer.setValue$1(Changer.scala:114)
	at com.mendix.basis.action.user.Changer.setMemberValue(Changer.scala:136)
	at com.mendix.basis.action.user.Changer.setMemberValue$(Changer.scala:102)
	at com.mendix.basis.action.user.ChangeAction.setMemberValue(ChangeAction.scala:9)
	at com.mendix.basis.action.user.Changer.changeMember(Changer.scala:85)
	at com.mendix.basis.action.user.Changer.$anonfun$changeMembers$3(Changer.scala:56)
	at com.mendix.basis.action.user.Changer.$anonfun$changeMembers$3$adapted(Changer.scala:55)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at com.mendix.basis.action.user.Changer.changeMembers(Changer.scala:55)
	at com.mendix.basis.action.user.Changer.changeMembers$(Changer.scala:43)
	at com.mendix.basis.action.user.ChangeAction.changeMembers(ChangeAction.scala:9)
	at com.mendix.basis.action.user.ChangeAction.executeAction(ChangeAction.scala:27)
	at com.mendix.basis.action.user.ChangeAction.executeAction(ChangeAction.scala:9)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:58)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.java:56)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:104)
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:103)
	at com.mendix.basis.component.ObjectManagementCore.change(ObjectManagementCore.scala:39)
	at com.mendix.basis.component.ObjectManagementCore.change$(ObjectManagementCore.scala:36)
	at com.mendix.basis.component.InternalCore.change(InternalCore.scala:24)
	at com.mendix.webui.requesthandling.helpers.StateHandling.$anonfun$addChangesToState$3(StateHandling.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at com.mendix.webui.requesthandling.helpers.StateHandling.addChangesToState(StateHandling.scala:159)
	at com.mendix.webui.requesthandling.helpers.StateHandling.initializeState(StateHandling.scala:116)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:44)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:42)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:46)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:54)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:46)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:120)
	at scala.util.Try$.apply(Try.scala:210)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:120)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:118)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$7(ContextHandling.scala:58)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:58)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:32)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:94)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:29)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:21)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:94)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:118)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:94)
	at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:115)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:106)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:79)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:37)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1(MxRuntimeConnector.scala:54)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1$adapted(MxRuntimeConnector.scala:54)
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.scala:54)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.scala:221)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeServlet.service(RuntimeServlet.scala:40)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by MichielArts** [comment]
Never mind, i noticed that the option to provide a context entity via association does not work. When i use the xpath-option it works. That is sufficent for me at this point in time.
